name: Build and Publish

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - release

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repo and submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build SDist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - name: Upload SDist
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: Build Wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
        os: [macos-latest, windows-latest, ubuntu-latest]
        architecture: [x86_64, arm64]
    steps:
      - name: Checkout out repo and submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.11.1
        with:
          python-version: ${{ matrix.python-version }}
          build-options: --arch 64
          platform: ${{ matrix.os }}

      - name: Upload Wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl

  upload_pypi:
    name: Upload to Test PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.LDPC_TEST_PYPI }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
