name: Build and Upload Python Package

on:
  push:
    branches:
      - release

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]  # Add more versions as needed
        architecture: [x64, arm64]  # Add arm64 for Apple Silicon

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools

      - name: Build wheel and sdist
        run: python setup.py sdist bdist_wheel

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist/*

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.LDPC_TEST_PYPI }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
