name: Build

on:
  push:
    branches:
     - release

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - name: Checkout out repo and submodules
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipx
        pipx ensurepath
        pipx install build
        pipx install twine

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz


  build_wheels:
    runs-on: ${{ matrix.os_dist.os }}
    env:
      CIBW_BUILD: "${{ matrix.os_dist.dist }}"
      # MACOSX_DEPLOYMENT_TARGET: "13.1"
      CIBW_ARCHS_MACOS: "arm64 x86_64"
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: delocate-wheel -w {dest_dir} -v {wheel}
    strategy:
      fail-fast: false
      matrix:
        os_dist: [
          # # macosx x86_64
          {os: macos-latest, dist: cp39-macosx_x86_64},
          # {os: macos-latest, dist: cp310-macosx_x86_64},
          # {os: macos-latest, dist: cp311-macosx_x86_64},
          # {os: macos-latest, dist: cp312-macosx_x86_64},
          # {os: macos-latest, dist: cp313-macosx_x86_64},


          # # # macosx arm64
          # {os: macos-latest, dist: cp39-macosx_arm64},
          # {os: macos-latest, dist: cp310-macosx_arm64},
          # {os: macos-latest, dist: cp311-macosx_arm64},
          # {os: macos-latest, dist: cp312-macosx_arm64},
          # {os: macos-latest, dist: cp313-macosx_arm64},

          # # # windows amd64
          # {os: windows-latest, dist: cp39-win_amd64},
          # {os: windows-latest, dist: cp310-win_amd64},
          # {os: windows-latest, dist: cp311-win_amd64},
          # {os: windows-latest, dist: cp312-win_amd64},
          # {os: windows-latest, dist: cp313-win_amd64},


          # # ubuntu x86_64
          # {os: ubuntu-latest, dist: cp39-manylinux_x86_64},
          # {os: ubuntu-latest, dist: cp310-manylinux_x86_64},
          # {os: ubuntu-latest, dist: cp311-manylinux_x86_64},
          # {os: ubuntu-latest, dist: cp312-manylinux_x86_64},
          # {os: ubuntu-latest, dist: cp313-manylinux_x86_64},


        ]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Run cibuildwheel
      uses: pypa/cibuildwheel@v2.23.1

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ github.run_id }}-${{ matrix.os_dist.dist }}
        path: ./wheelhouse/*.whl


  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout out repo and submodules
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Download SDist
      uses: actions/download-artifact@v4
      with:
        name: sdist
        path: dist

    - name: Download Wheels
      uses: actions/download-artifact@v4
      with:
        name: wheels
        path: dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_PASSWORD }}
        skip_existing: true
        verbose: true